version: "3.4"

services:
  mysql:
      image: mysql:latest
      restart: always
      environment:
        MYSQL_DATABASE: 'falabella'
        MYSQL_USER: 'hectoralvarado'
        MYSQL_PASSWORD: 'hectoralvarado123'
        MYSQL_ROOT_PASSWORD: 'hectoralvarado123'
      ports:
        - '3306:3306'
      expose:
        - '3306'
      volumes:
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local